#!/bin/bash
# Script to display WSL IP and commands to run on Windows

WSL_IP=$(hostname -I | awk '{print $1}')

echo "============================================"
echo "WSL Port Forwarding Setup Instructions"
echo "============================================"
echo ""
echo "1. Your WSL IP Address: $WSL_IP"
echo "2. Server is running on: 0.0.0.0:3000"
echo ""
echo "============================================"
echo "OPTION 1: Use PowerShell Script (Recommended)"
echo "============================================"
echo ""
echo "Run this in PowerShell AS ADMINISTRATOR:"
echo ""
echo "cd $(wslpath -w $(pwd))"
echo ".\\setup-wsl-port-forward.ps1"
echo ""
echo "============================================"
echo "OPTION 2: Manual Setup"
echo "============================================"
echo ""
echo "Run these commands in PowerShell AS ADMINISTRATOR:"
echo ""
echo "# Remove old forwarding"
echo "netsh interface portproxy delete v4tov4 listenport=3000 listenaddress=0.0.0.0"
echo ""
echo "# Add new forwarding"
echo "netsh interface portproxy add v4tov4 listenport=3000 listenaddress=0.0.0.0 connectport=3000 connectaddress=$WSL_IP"
echo ""
echo "# Add firewall rule"
echo "New-NetFirewallRule -DisplayName 'WSL Port 3000' -Direction Inbound -LocalPort 3000 -Protocol TCP -Action Allow"
echo ""
echo "============================================"
echo "OPTION 3: Access via WSL IP directly"
echo "============================================"
echo ""
echo "Try accessing from Windows: http://$WSL_IP:3000"
echo ""
echo "============================================"
echo "To verify port forwarding (PowerShell):"
echo "netsh interface portproxy show all"
echo "============================================"
